"""Optimization primitives for fixed and belief-aware predictive control."""

from .joint_prediction import JointARXPredictionModel, assemble_joint_arx_prediction
from .linear_mpc import (
    LinearMPC,
    LinearMPCResult,
    LinearPredictionModel,
    MPCBounds,
    MPCWeights,
    linearize_grid_ibr,
)
from .mpc_problem import (
    ARX_CONSTANT_INDEX,
    ARX_POWER_INDEX,
    GRID_FREQUENCY_INDEX,
    GRID_INTEGRAL_INDEX,
    REQUIRED_NATIVE_COMPONENT_COUNT,
    SDBMPCBounds,
    SDBMPCConfig,
    SDBMPCMode,
    SDBMPCProblem,
    SDBMPCProblemCache,
    SDBMPCWeights,
    build_sd_bmpc_problem,
    credible_mode_indices,
    modes_from_library,
)
from .solver_utils import (
    DEFAULT_SOLVER_PRIORITY,
    SolverAttempt,
    SolverOutcome,
    SolverResult,
    shift_warm_start_sequence,
    solve_cvxpy_problem,
    solver_version,
)

__all__ = [
    "ARX_CONSTANT_INDEX",
    "ARX_POWER_INDEX",
    "DEFAULT_SOLVER_PRIORITY",
    "GRID_FREQUENCY_INDEX",
    "GRID_INTEGRAL_INDEX",
    "JointARXPredictionModel",
    "LinearMPC",
    "LinearMPCResult",
    "LinearPredictionModel",
    "MPCBounds",
    "MPCWeights",
    "REQUIRED_NATIVE_COMPONENT_COUNT",
    "SDBMPCBounds",
    "SDBMPCConfig",
    "SDBMPCMode",
    "SDBMPCProblem",
    "SDBMPCProblemCache",
    "SDBMPCWeights",
    "SolverAttempt",
    "SolverOutcome",
    "SolverResult",
    "build_sd_bmpc_problem",
    "credible_mode_indices",
    "linearize_grid_ibr",
    "assemble_joint_arx_prediction",
    "modes_from_library",
    "shift_warm_start_sequence",
    "solve_cvxpy_problem",
    "solver_version",
]
